### ISSUE TITLE
Failed to initialize the Alertmanager error

### ISSUE THREAD

**Issue by turboazot** [grafana/mimir#4688] opened 2023-04-07 19:30 UTC
#### Describe the bug
When I deploy mimir helm chart with `alertmanager.enabled: true`. After alertmanager is started it shows
```
Failed to initialize the Alertmanager error
```

and in logs I can see this output:
```
mkdir /alertmanager: permissions denied
```

#### To Reproduce

1. Deploy mimir helm chart `4.2.0` version with `alertmanager.enabled: true` value
2. Port forward mimir-alertmanager-0 8080 port
3. Go to `/alertmanager` path and you will see `Failed to initialize the Alertmanager error`

#### Environment

- Infrastructure: GKE Kubernetes v1.24.9-gke.3200
- Deployment tool: helm

#### Additional Context

Actually, I fixed this by manually mounting pvc to `/alertmanager` path. But it would be great to use helm chart functionality out of the box

**Comment by andreimiclea99** [comment] 2023-04-10 05:37
I faced the exactly the same issue ( on the same infrastructure), would be great indeed to to use helm chart functionality out of the box.

**Comment by dimitarvdimitrov** [comment] 2023-07-11 10:08
Apologies for the delay. Unfortunately, I am failing to reproduce this. All the necessary volumes for alertmanager should be already mounted on the alertmanager pods, and nothing should be stored in `/alertmanager` using the default configuration. 

@turboazot can you share your values file (or helm CLI parameters)?

**Comment by turboazot** [comment] 2023-07-12 15:16
@dimitarvdimitrov sorry, we already migrated to grafana alerts

**Comment by dimitarvdimitrov** [comment] 2023-07-12 15:50
I'll close this because I can't reproduce it. If someone faces this problem again, feel free to reopen

**Closed by dimitarvdimitrov** 2023-07-12 15:50 UTC
Labels: component/alertmanager, helm

**Comment by santhosh-sathishkumar** [comment] 2024-07-13 14:07
I am getting the same error. Using GCS as a backend with small.yaml
`msg="unable to initialize the Alertmanager with a fallback configuration" user=anonymous err="mkdir /alertmanager: read-only file system"`
