### ISSUE TITLE
Flaky ruler test `TestRulerEvaluationDelay`

### ISSUE THREAD

**Issue by ortuman** [grafana/mimir#6475] opened 2023-10-24 11:17 UTC
From https://github.com/grafana/mimir/actions/runs/6625716540/job/17997547414?pr=6474#step:15:2124

```
 === RUN   TestRulerEvaluationDelay
11:05:11 Starting minio-9000
11:05:12 Ports for container: e2e-mimir-test-minio-9000 Mapping: map[9000:33048]
11:05:12 Started minio-9000
11:05:12 Starting mimir
11:05:13 Ports for container: e2e-mimir-test-mimir Mapping: map[9009:33049]
11:05:13 Started mimir
    ruler_test.go:312: 
        	Error Trace:	/home/runner/work/mimir/mimir/integration/ruler_test.go:312
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 4
        	Test:       	TestRulerEvaluationDelay
11:05:25 Killing mimir
11:05:25 Killing minio-9000
11:05:26 Killed minio-9000
11:05:26 Killed mimir
11:05:26 error while removing sharedDir /home/runner/work/mimir/mimir/integration/e2e_integration_test1359927339 err: unlinkat /home/runner/work/mimir/mimir/integration/e2e_integration_test1359927339/rule_tmp/anonymous/ns: permission denied
--- FAIL: TestRulerEvaluationDelay (14.92s)
```

**Comment by zenador** [comment] 2023-10-31 18:57
Duplicate of https://github.com/grafana/mimir/issues/4857

**Closed** 2023-12-04 16:56 UTC
Labels: type/tests
