### ISSUE TITLE
streaming store-gateway: series and chunks limits are enforced later

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#3878] opened 2023-01-09 09:58 UTC
### Problem
In the streaming implementation the store-gateway enforces the chunks and series limits for each batch and then sends the batch to the querier. In contrast the default implementation first counts all series and chunks and then proceeds to load and send them to the querier. 

In the streaming implementation some chunks and series will be sent before the limit is hit. 

### Impact 

In cases where the limit is hit for a large % of queries this results in higher CPU usage and requests to cache/bucket compared to non-streaming store-gateway.

### Solutions?

Limiting series before starting is trivial because we have a list of all series we'll load (for now).

But limiting chunks is less trivial. We can maybe estimate the number of chunks each series will have based on the numbers of chunks per series in the first batch. Unfortunately, this will negatively impact requests where the # of chunks is significantly reduced because the time range in the request is narrow (e.g. selecting only 1 hour instead of whole 24h)

**Comment by pracucci** [comment] 2023-01-09 11:28
> But limiting chunks is less trivial. We can maybe estimate the number of chunks each series will have based on the numbers of chunks per series in the first batch. Unfortunately, this will negatively impact requests where the # of chunks is significantly reduced because the time range in the request is narrow (e.g. selecting only 1 hour instead of whole 24h)

The query time range could be taken in the equation too, but the problem is that we don't know how much series are churning and the sample rate. An idea could be computing this estimation after the 1st batch is processed, and the optimistically project it for the following batches in advance.

**Comment by pracucci** [comment] 2023-01-20 15:15
> Limiting series

Currently series are not limited. The limit is always initialized to 0 (disabled), but @duricanikolic is working on it (see https://github.com/grafana/mimir/issues/3382), so we should try to improve it cause series will be soon limited here as well.

**Comment by dimitarvdimitrov** [comment] 2023-04-17 10:41
> An idea could be computing this estimation after the 1st batch is processed, and the optimistically project it for the following batches in advance.

So we can use the first batch to estimate the churn rate and the number of selected chunks per series, right?

For series limit estimation: We can take a look at the number of series consumed from each batch and then compare with the number of series that we actually returned. We can use this to project the total number of series we will return given the total number of postings from all blocks.

For chunks limit estimation: we can see how many chunks per series were eventually returned and project this for the number of series we got from the previous estimation.

I'm tempted to also have some tolerance for incorrect estimations. Maybe if we're within the same order of magnitude as the limit, we can still attempt to complete the request?

**Comment by pracucci** [comment] 2023-04-19 11:01
> I'm tempted to also have some tolerance for incorrect estimations. Maybe if we're within the same order of magnitude as the limit, we can still attempt to complete the request?

Yes, definitely. There should be an high tolerance. Even a 2x tolerance. We just want to reject the request if the estimation is significantly higher than the limit.

**Comment by pracucci** [comment] 2024-05-13 15:40
@charleskorn Should we close this issue given the work done in https://github.com/grafana/mimir/pull/5765 ?

**Comment by charleskorn** [comment] 2024-05-14 02:54
> @charleskorn Should we close this issue given the work done in #5765 ?

Yes we should.

**Closed by charleskorn** 2024-05-14 02:54 UTC
Labels: component/store-gateway, ease-of-use
