### ISSUE TITLE
Docs: Eliminate errors derived from Mimir Helm chart’s custom.yaml as it is currently described

### ISSUE THREAD

**Issue by majerus1223** [grafana/mimir#5550] opened 2023-07-19 14:53 UTC
#### Describe the bug
(https://grafana.com/docs/helm-charts/mimir-distributed/latest/get-started-helm-charts/#generate-some-metrics-for-testing) instructs you to create a custom.yaml and apply it to the cluster. When following the guide on multiple systems errors for CRDS are thrown. 

#### To Reproduce

Build new rancher desktop cluster
follow steps until you hit the custom.yaml section
watch for errors

#### Expected behavior

The command to execute as shown in documentation without error https://grafana.com/docs/helm-charts/mimir-distributed/latest/get-started-helm-charts/#generate-some-metrics-for-testing

#### Environment

- rancher desktop 1.9
- k8s version 1.27.3

#### Additional Context

`helm -n mimir-test upgrade mimir grafana/mimir-distributed -f custom.yaml`
```
Error: UPGRADE FAILED: [resource mapping not found for name: "mimir-meta-monitoring" namespace: "mimir-test" from "": no matches for kind "GrafanaAgent" in ver
sion "monitoring.grafana.com/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-meta-monitoring" namespace: "mimir-test" from "": no matches for kind "LogsInstanc
e" in version "monitoring.grafana.com/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-meta-monitoring" namespace: "mimir-test" from "": no matches for kind "MetricsInst
ance" in version "monitoring.grafana.com/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-meta-monitoring" namespace: "mimir-test" from "": no matches for kind "PodLogs" in
 version "monitoring.grafana.com/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-alertmanager" namespace: "mimir-test" from "": no matches for kind "ServiceMonitor
" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-compactor" namespace: "mimir-test" from "": no matches for kind "ServiceMonitor" i
n version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-distributor" namespace: "mimir-test" from "": no matches for kind "ServiceMonitor"
 in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-ingester" namespace: "mimir-test" from "": no matches for kind "ServiceMonitor" in
 version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-k8s-ksm" namespace: "mimir-test" from "": no matches for kind "ServiceMonitor" in
version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-k8s-kubelet-cadvisor" namespace: "mimir-test" from "": no matches for kind "Servic
eMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-overrides-exporter" namespace: "mimir-test" from "": no matches for kind "ServiceM
onitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-querier" namespace: "mimir-test" from "": no matches for kind "ServiceMonitor" in
version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-query-frontend" namespace: "mimir-test" from "": no matches for kind "ServiceMonit
or" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-query-scheduler" namespace: "mimir-test" from "": no matches for kind "ServiceMoni
tor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-ruler" namespace: "mimir-test" from "": no matches for kind "ServiceMonitor" in ve
rsion "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mimir-store-gateway" namespace: "mimir-test" from "": no matches for kind "ServiceMonito
r" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first]
```

**Comment by krajorama** [comment] 2023-07-20 12:39
Should be addressed by #5391 , the new text is in version `next` at the moment: https://grafana.com/docs/helm-charts/mimir-distributed/next/get-started-helm-charts/#generate-some-metrics-for-testing

**Comment by majerus1223** [comment] 2023-07-20 21:33
There might be an issue with the CRDs for the grafana agent. Working on testing it currently will see if this keeps the tutorial from completing. 

`PS C:\Users\james\Monitoring> kubectl apply -f .\agent\production\operator\crds\
customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/integrations.monitoring.grafana.com created
customresourcedefinition.apiextensions.k8s.io/logsinstances.monitoring.grafana.com created
customresourcedefinition.apiextensions.k8s.io/metricsinstances.monitoring.grafana.com created
customresourcedefinition.apiextensions.k8s.io/podlogs.monitoring.grafana.com created
The CustomResourceDefinition "grafanaagents.monitoring.grafana.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

**Comment by majerus1223** [comment] 2023-07-20 21:35
Yea, looks like it fails.. 


`PS C:\Users\james\Monitoring> helm -n mimir-test upgrade mimir grafana/mimir-distributed -f .\custom.yaml
Error: UPGRADE FAILED: resource mapping not found for name: "mimir-meta-monitoring" namespace: "mimir-test" from "": no matches for kind "GrafanaAgent" in version "monitoring.gr
afana.com/v1alpha1"
ensure CRDs are installed first`



Going to try to use this see if i can work around it. https://github.com/grafana/agent/issues/4379

**Comment by majerus1223** [comment] 2023-07-20 21:53
Got this working by using 

`kubectl create -f \operator\crds\ 


`PS` C:\Users\james\Monitoring> kubectl create -f .\agent\production\operator\crds\
customresourcedefinition.apiextensions.k8s.io/grafanaagents.monitoring.grafana.com created
Error from server (AlreadyExists): error when creating "agent\\production\\operator\\crds\\monitoring.coreos.com_podmonitors.yaml": customresourcedefinitions.apiextensions.k8s.i
o "podmonitors.monitoring.coreos.com" already exists
Error from server (AlreadyExists): error when creating "agent\\production\\operator\\crds\\monitoring.coreos.com_probes.yaml": customresourcedefinitions.apiextensions.k8s.io "pr
obes.monitoring.coreos.com" already exists
Error from server (AlreadyExists): error when creating "agent\\production\\operator\\crds\\monitoring.coreos.com_servicemonitors.yaml": customresourcedefinitions.apiextensions.k
8s.io "servicemonitors.monitoring.coreos.com" already exists
Error from server (AlreadyExists): error when creating "agent\\production\\operator\\crds\\monitoring.grafana.com_integrations.yaml": customresourcedefinitions.apiextensions.k8s
.io "integrations.monitoring.grafana.com" already exists
Error from server (AlreadyExists): error when creating "agent\\production\\operator\\crds\\monitoring.grafana.com_logsinstances.yaml": customresourcedefinitions.apiextensions.k8
s.io "logsinstances.monitoring.grafana.com" already exists
Error from server (AlreadyExists): error when creating "agent\\production\\operator\\crds\\monitoring.grafana.com_metricsinstances.yaml": customresourcedefinitions.apiextensions
.k8s.io "metricsinstances.monitoring.grafana.com" already exists
Error from server (AlreadyExists): error when creating "agent\\production\\operator\\crds\\monitoring.grafana.com_podlogs.yaml": customresourcedefinitions.apiextensions.k8s.io "
podlogs.monitoring.grafana.com" already exists`

```
PS C:\Users\james\Monitoring> kubectl replace -f .\agent\production\operator\crds\
customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com replaced
customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com replaced
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com replaced
customresourcedefinition.apiextensions.k8s.io/grafanaagents.monitoring.grafana.com replaced
customresourcedefinition.apiextensions.k8s.io/integrations.monitoring.grafana.com replaced
customresourcedefinition.apiextensions.k8s.io/logsinstances.monitoring.grafana.com replaced
customresourcedefinition.apiextensions.k8s.io/metricsinstances.monitoring.grafana.com replaced
customresourcedefinition.apiextensions.k8s.io/podlogs.monitoring.grafana.com replaced
PS C:\Users\james\Monitoring> helm -n mimir-test upgrade mimir grafana/mimir-distributed -f .\custom.yaml
Release "mimir" has been upgraded. Happy Helming!
NAME: mimir
LAST DEPLOYED: Thu Jul 20 16:52:01 2023
NAMESPACE: mimir-test
STATUS: deployed
```

Helpful article https://medium.com/pareture/kubectl-install-crd-failed-annotations-too-long-2ebc91b40c7d

**Comment by majerus1223** [comment] 2023-07-23 03:06
Found a few more issues.. 

When attempting to configure nginx as it is shown in the documentation there is a refrence to nginx. If you have a ingress class that is say traefik it fails. Your better off not defining it and letting the cluster default option take place. 

Additionally the documents do not provide a way to even tell if this is working smoothly. One would think that just going to mimir.customdomain.com would show something however it just downloads a file with data of "OK". The link in the docs show mimir.customdoimain.com/prometheus which also throws a 404. Overall for anyone trying to get started your are now pulling your hair out. The docs should say validate with the following. http://mimir.utek.co/prometheus/api/v1/status/buildinfo , which will at least show the build information. (The only way i found this was going into github discussions, google doesnt pick this up)
https://github.com/grafana/mimir/discussions/5010#discussioncomment-5903811

Error Location: https://grafana.com/docs/helm-charts/mimir-distributed/next/get-started-helm-charts/#advanced-setup-with-external-access

This
```
nginx:
  ingress:
    enabled: true
    hosts:
      - host: mimir.customdomain.com
        paths:
          - path: /
            pathType: Prefix
    tls:

```
Instead of
```
nginx:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: mimir.customdomain.com
        paths:
          - path: /
            pathType: Prefix
    tls:
```

**Comment by majerus1223** [comment] 2023-07-28 13:24
I have a few more things to write up about this as well finally got it going after working on it for quite some time.

**Comment by francoposa** [comment] 2023-07-28 16:14
Yeah I can package some of these changes up so looks like so far
1. ~~Issues caused by CRDs not already being installed~~ - already fixed in the next docs release
2.  Installation of large CRDS can fail on `kubectl apply` due to kubernetes config diffing exceeding some size constraint
    i. can be fixed by using `kubectl create` instead - will update docs
3. recommended custom values to apply the ingress resource may reference an ingressClassName that does not exist on the cluster, if you are not using `ingress-nginx` controller, or if you deployed `ingress-nginx` with a different name.

Looking at the question about `ingressClassName` I have been doing some research on this to understand.

So essentially as it stands we say "make sure you have an ingress controller installed, such as `ingress-nginx`.
And then we provide a YAML to reference the ingress controller name, _assuming_ that you indeed were using nginx ingress controller _and_ deployed it with `ingressClassName: nginx`.

So instead we might want something like this in the docs:
```yaml
nginx:
  ingress:
    enabled: true
    # ingressClassName may be used to reference a non-default ingressClass for your cluster
    # ingressClassName: nginx
    hosts:
      - host: mimir.customdomain.com
        paths:
          - path: /
            pathType: Prefix
    tls:
```

**Closed** 2023-08-18 13:54 UTC
Labels: type/docs
