### ISSUE TITLE
Goroutine leak in TestStoreGateway_YYY

### ISSUE THREAD

**Issue by narqo** [grafana/mimir#9009] opened 2024-08-15 07:23 UTC
We've noticed a failure in the CI, that reported a goroutine leak in a couple of tests for `storegateway/indexheader.(*LazyBinaryReader)` ([CI logs](https://github.com/grafana/mimir/actions/runs/10396338913/job/28790161079))

@dimitarvdimitrov that seems related to the recent changes from #8380, right?

```
--- FAIL: TestStoreGateway_BlocksSyncWithDefaultSharding_RingTopologyChangedAfterScaleUp (16.89s)
    leak.go:14: found unexpected goroutines:
        [Goroutine 2040876 in state select, with github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop on top of the stack:
        github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop(0xc000e00ea0)
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:341 +0x17f
        created by github.com/grafana/mimir/pkg/storegateway/indexheader.NewLazyBinaryReader in goroutine 2040872
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:167 +0xc4b
        ]
--- FAIL: TestStoreGateway_ShouldSupportLoadRingTokensFromFile (1.42s)
    leak.go:14: found unexpected goroutines:
        [Goroutine 2040876 in state select, with github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop on top of the stack:
        github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop(0xc000e00ea0)
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:341 +0x17f
        created by github.com/grafana/mimir/pkg/storegateway/indexheader.NewLazyBinaryReader in goroutine 2040872
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:167 +0xc4b
--- FAIL: TestStoreGateway_Series_QueryShardingShouldGuaranteeSeriesShardingConsistencyOverTheTime (0.91s)
    leak.go:14: found unexpected goroutines:
        [Goroutine 2040876 in state select, with github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop on top of the stack:
        github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop(0xc000e00ea0)
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:341 +0x17f
        created by github.com/grafana/mimir/pkg/storegateway/indexheader.NewLazyBinaryReader in goroutine 2040872
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:167 +0xc4b
        ]
--- FAIL: TestStoreGateway_Series_QueryShardingConcurrency (2.58s)
    leak.go:14: found unexpected goroutines:
        [Goroutine 2040876 in state select, with github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop on top of the stack:
        github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop(0xc000e00ea0)
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:341 +0x17f
        created by github.com/grafana/mimir/pkg/storegateway/indexheader.NewLazyBinaryReader in goroutine 2040872
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:167 +0xc4b
        ]
--- FAIL: TestStoreGateway_SeriesQueryingShouldEnforceMaxChunksPerQueryLimit (3.36s)
    leak.go:14: found unexpected goroutines:
        [Goroutine 2040876 in state select, with github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop on top of the stack:
        github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop(0xc000e00ea0)
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:341 +0x17f
        created by github.com/grafana/mimir/pkg/storegateway/indexheader.NewLazyBinaryReader in goroutine 2040872
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:167 +0xc4b
        ]
--- FAIL: TestPreloadingSetIterator (1.73s)
    leak.go:14: found unexpected goroutines:
        [Goroutine 2040876 in state select, with github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop on top of the stack:
        github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop(0xc000e00ea0)
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:341 +0x17f
        created by github.com/grafana/mimir/pkg/storegateway/indexheader.NewLazyBinaryReader in goroutine 2040872
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:167 +0xc4b
        ]
--- FAIL: TestPreloadingSetIterator_ContextCancellation (0.45s)
    leak.go:14: found unexpected goroutines:
        [Goroutine 2040876 in state select, with github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop on top of the stack:
        github.com/grafana/mimir/pkg/storegateway/indexheader.(*LazyBinaryReader).controlLoop(0xc000e00ea0)
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:341 +0x17f
        created by github.com/grafana/mimir/pkg/storegateway/indexheader.NewLazyBinaryReader in goroutine 2040872
        	/__w/mimir/mimir/pkg/storegateway/indexheader/lazy_binary_reader.go:167 +0xc4b
        ]
FAIL
FAIL	github.com/grafana/mimir/pkg/storegateway	378.572s

```

**Comment by dimitarvdimitrov** [comment] 2024-08-15 09:40
I was able to reproduce locally by running `TestStoreGateway_BlocksSyncWithDefaultSharding_RingTopologyChangedAfterScaleUp`

**Comment by dimitarvdimitrov** [comment] 2024-08-15 10:40
I got as far as confirming that `LazyBinaryReader.Close()` is not invoked at all. From the debug logs I added I figured that this happens because [`blockSet.add()`](https://github.com/grafana/mimir/blob/79953c8aff2effd9c896a5dbb4e121526f7cb83c/pkg/storegateway/bucket.go#L497) is called while [`blockSet.closeAll()`](https://github.com/grafana/mimir/blob/79953c8aff2effd9c896a5dbb4e121526f7cb83c/pkg/storegateway/bucket.go#L1904) is running. basically we're adding a block while we're shutting down.

I think the only reason this might happen is that the sync (which transitively calls `blockSet.add()`) [is interrupted via a context cancellation](https://github.com/grafana/mimir/blob/79953c8aff2effd9c896a5dbb4e121526f7cb83c/pkg/storegateway/bucket.go#L332). I'm verifying that

**Comment by dimitarvdimitrov** [comment] 2024-08-15 11:01
> I think the only reason this might happen is that the sync (which transitively calls `blockSet.add()`) [is interrupted via a context cancellation](https://github.com/grafana/mimir/blob/79953c8aff2effd9c896a5dbb4e121526f7cb83c/pkg/storegateway/bucket.go#L332). I'm verifying that

even adding proper return there doesn't sovle the issue. I'm out of time today for this, so I'll continue some other day. 

These are my debugging logs https://github.com/grafana/mimir/commit/7a1bb1883fcb50e381783f505a8abf9188664a24

and this is how I ran the test 

```
go test -v -paniconexit0 -run ^\QTestStoreGateway_BlocksSyncWithDefaultSharding_RingTopologyChangedAfterScaleUp\E$ -count=100 -failfast
```

the main problem is that reproducing this takes minutes because the test is slow.

**Comment by dimitarvdimitrov** [comment] 2024-08-19 14:05
I know a bit more: the race is between closing the BucketStore and doing a periodic sync.

<details><summary>Details</summary>
<p>

```
bucketStore 0x14001380420 start syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).InitialSync
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x1400125cf30 added block 0x14000a94780
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x14000cecab0 added block 0x14000ca8500
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x1400096b710 added block 0x14000e96140
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x14001182d80 added block 0x14000a9a8c0
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x140005b4480 added block 0x14000e963c0
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x140005a41b0 added block 0x14000864000
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x14000c1a000 added block 0x14000a94140
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x140005b4510 added block 0x14000e96500
bucketStore 0x14001380420 end syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).InitialSync
bucketStore 0x14001380420 start syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).SyncBlocks
bucketStore 0x14001380420 end syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).SyncBlocks
bucketStore 0x14001380420 start syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).SyncBlocks
bucketStore 0x14001380420 end syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).SyncBlocks
bucketStore 0x14001380420 start syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).SyncBlocks
bucketStore 0x14001380420 end syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).SyncBlocks
bucketStore 0x14001380420 start syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).SyncBlocks
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x14001482000 added block 0x14000d8c640
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x1400201c240 added block 0x14000fc6140
bucketStore 0x14001380420 end syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).SyncBlocks
bucketStore 0x14001380420 start syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).SyncBlocks
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x1400201c990 added block 0x14000fc6780
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x14002312990 added block 0x14001321400
bucketStore 0x14001380420 blockSet 0x14002113180 starting to close blocks
bucketStore 0x14001380420 blockSet 0x14002113180 context done; waiting for all addBlocks to finish
bucketStore 0x14001380420 blockSet 0x14002113180 indexHeaderReader 0x14001483050 added block 0x14000d44500
bucketStore 0x14001380420 blockSet 0x14002113180 closed all blocks
bucketStore 0x14001380420 end syncBlocks from github.com/grafana/mimir/pkg/storegateway.(*BucketStore).SyncBlocks
```

</p>
</details> 

`BucketStore.stop` is called while `BucketStore.SyncBlocks` is executing:

https://github.com/grafana/mimir/blob/c5c3b4e36119ff825037b69ec18706f4f41fb88f/pkg/storegateway/bucket.go#L269-L276

https://github.com/grafana/mimir/blob/c5c3b4e36119ff825037b69ec18706f4f41fb88f/pkg/storegateway/bucket.go#L302-L304

My previous understanding was that this wasn't possible because stopping the bucket store and periodic sync were synchronised by the StoreGateway [here](https://github.com/grafana/mimir/blob/7b64444d81683042ac14b287876bfd1186c40062/pkg/storegateway/gateway.go#L279-L308)

**Comment by dimitarvdimitrov** [comment] 2024-08-19 15:12
> My previous understanding was that this wasn't possible because stopping the bucket store and periodic sync were synchronised by the StoreGateway [here](https://github.com/grafana/mimir/blob/7b64444d81683042ac14b287876bfd1186c40062/pkg/storegateway/gateway.go#L279-L308)

That assumption was wrong and I think I found the bug - `BucketStores` are started with the `context.Context` of the process. That context gets cancelled as soon as the process receives a SIGTERM/SIGINT. This means this assumption was wrong. I'm now running the test with this fix 

```diff
diff --git a/pkg/storegateway/gateway.go b/pkg/storegateway/gateway.go
index 14f4640858..fd2044d515 100644
--- a/pkg/storegateway/gateway.go
+++ b/pkg/storegateway/gateway.go
@@ -253,7 +253,7 @@ func (g *StoreGateway) starting(ctx context.Context) (err error) {
 	// At this point, the instance is registered with some tokens
 	// and we can start the bucket stores.
 	g.bucketSync.WithLabelValues(syncReasonInitial).Inc()
-	if err = services.StartAndAwaitRunning(ctx, g.stores); err != nil {
+	if err = services.StartAndAwaitRunning(context.Background(), g.stores); err != nil {
 		return errors.Wrap(err, "starting bucket stores")
 	}
```



One possible scenario where this would have  a negative effect outside of tests is that we shut down the BucketStore before waiting for all queries to finish. I couldn't find related logs for this (I was looking for `lazy reader is closed; this shouldn't happen` logs)

I opened https://github.com/grafana/mimir/pull/9048 with the fix. Previously the test failed 3 out of 70 runs (once every ~23 runs). I'm currently at >60 runs (my test logs got truncated) and haven't reproduced yet. Waiting to hit 100 and will turn the PR as ready for review.

**Closed** 2024-08-26 08:18 UTC
Labels: type/tests
