### ISSUE TITLE
[Helm Chart] Ingester : use prestop hook on ingester pods to call /ingester/shutdown

### ISSUE THREAD

**Issue by SamuelBagattin** [grafana/mimir#3004] opened 2022-09-21 09:09 UTC
#### Is your feature request related to a problem? Please describe.

I have came across [the ingester documentation about scaling down](https://grafana.com/docs/mimir/latest/operators-guide/run-production-environment/scaling-out/#scaling-down-ingesters), it is recommended to call `/ingester/shutdown` before sending a SIGTERM or SIGINT.
From what I understand, this API call can only be done manually.

This causes data loss when performing a rolling deployment on the ingester statefulset.

#### Describe the solution you'd like

Would it be appropriate to add a HTTP preStop lifecycle hook on the ingester pod that calls the `/ingester/shutdown` API ?

#### Describe alternatives you've considered

Currently we call the shutdown endpoint manually.

**Comment by dimitarvdimitrov** [comment] 2022-09-22 15:31
> This causes data loss when performing a rolling deployment on the ingester statefulset.

This shouldn't be the case. This endpoint flushes blocks from local storage to the object store. If the ingester is only restarting and comes back up using the same persistent volume, then no data should be lost.

It's required to call this endpoint when the persistent volume will no longer be mounted to an ingester and will be deleted. This is the case for scale downs, but not rolling restarts.

Can you give more details about your use case?

**Comment by sysedwinistrator** [comment] 2022-09-26 10:04
Does the config option `ingester.ring.unregister_on_shutdown` do the same thing as the`/ingester/shutdown` API endpoint, or does it only unregister the ingester from the ring but not flush the blocks from local storage?  
Anyway, this option is enabled by default in the upstream config, but disabled by default in the Helm chart. You can override it using the `structuredConfig` option in the Helm values (introduced with Helm chart version 3.0.0):
```yaml
mimir:
  structuredConfig:
    ingester:
      ring:
       unregister_on_shutdown: true
```
I've done this because sometimes the ingesters wouldn't re-register after a restart and complain that there already is an ingester of the same name.

**Comment by dimitarvdimitrov** [comment] 2022-09-26 16:41
to achieve the same as `POST /ingester/shutdown` automatically you need to set `flush_blocks_on_shutdown` too.

```yaml
mimir:
  structuredConfig:
    ingester:
      ring:
       unregister_on_shutdown: true
    blocks_storage:
      tsdb:
        flush_blocks_on_shutdown: true
```

That will make shutdowns slower, but should guarantee no data loss in case of lost PVCs

But I still don't understand the original issue that @SamuelBagattin posted

**Comment by SamuelBagattin** [comment] 2022-09-26 16:54
@sysedwinistrator @dimitarvdimitrov, thanks for your replies, I now understand why I have theses issues.
@dimitarvdimitrov you pointed the issue : currently I do not have PVs attached to ingesters, that is why i am losing data after a rolling deployment.

> to achieve the same as `POST /ingester/shutdown` automatically you need to set `flush_blocks_on_shutdown` too.
> 
> ```yaml
> mimir:
>   structuredConfig:
>     ingester:
>       ring:
>        unregister_on_shutdown: true
>     blocks_storage:
>       tsdb:
>         flush_blocks_on_shutdown: true
> ```
> 
> That will make shutdowns slower, but should guarantee no data loss in case of lost PVCs
> 
> But I still don't understand the original issue that @SamuelBagattin posted

The solution you proposed would work too.

Do you have any advice on which solution is better ? Persistent volumes or unregister_on_shutdown + flush_blocks_on_shutdown ?

**Comment by dimitarvdimitrov** [comment] 2022-09-26 17:18
Persistent volumes would be better.

First, because even if you flush data to object storage on shutdown, queries would still expect to find this data on the ingesters and not on the object storage. So you wouldn't see the flushed data in graphs until queries consider it old enough to look for in the object store.

Second, they also allow ingesters to restart with less "noise" that other components have to deal with. Otherwise, restarting will be like removing and adding a new ingester, which can lead to rebalancing of series across ingesters, which add unnecessary load for the next 2-3 hours after the restart.

I'm closing this since the issue is about local configuration vs an issue with mimir.

**Closed by dimitarvdimitrov** 2022-09-26 17:18 UTC
Labels: helm

**Comment by sysedwinistrator** [comment] 2022-09-28 15:58
> First, because even if you flush data to object storage on shutdown, queries would still expect to find this data on the ingesters and not on the object storage. So you wouldn't see the flushed data in graphs until queries consider it old enough to look for in the object store.

Do I understand correctly that there currently is no way of removing an ingester without service degradation on the query side?

> Second, they also allow ingesters to restart with less "noise" that other components have to deal with. Otherwise, restarting will be like removing and adding a new ingester, which can lead to rebalancing of series across ingesters, which add unnecessary load for the next 2-3 hours after the restart.

I guess this explains why we had stability issues when we tried to autoscale the ingester (we also enabled the shutdown hook in that case). Now it's also clear to me why autoscaling the ingester is supported by the Helm chart.
