### ISSUE TITLE
segfault (panic) in 2.5.0 store gateway

### ISSUE THREAD

**Issue by Packetslave** [grafana/mimir#3759] opened 2022-12-17 20:40 UTC
#### Describe the bug

Store Gateway (2.5.0) is panic'ing randomly. Seems to be in `pkg/util/merger.go`.  Stack trace is attached.

[segfault.txt](https://github.com/grafana/mimir/files/10252718/segfault.txt)

Excerpt:
```
unexpected fault address 0x7f49341ae5fc
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f49341ae5fc pc=0x4032f1]

goroutine 25642886 [running]:
runtime.throw({0x1faba5c?, 0xc0500d6bb0?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0bbb9ec98 sp=0xc0bbb9ec68 pc=0x43a07d
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:842 +0x2c5 fp=0xc0bbb9ece8 sp=0xc0bbb9ec98 pc=0x450a25
memeqbody()
	/usr/local/go/src/internal/bytealg/equal_amd64.s:108 +0xd1 fp=0xc0bbb9ecf0 sp=0xc0bbb9ece8 pc=0x4032f1
github.com/grafana/mimir/pkg/util.mergeTwoStringSlices({0xc003fa7400, 0xa, 0x40}, {0xc0500d6580, 0xa, 0xb})
	/__w/mimir/mimir/pkg/util/merger.go:74 +0x155 fp=0xc0bbb9eda0 sp=0xc0bbb9ecf0 pc=0x167da75
github.com/grafana/mimir/pkg/util.MergeSlices({0xc0cbfa9570, 0x606?, 0x9c6})
	/__w/mimir/mimir/pkg/util/merger.go:63 +0xd8 fp=0xc0bbb9edf8 sp=0xc0bbb9eda0 pc=0x167d898

...

github.com/grafana/mimir/pkg/storegateway.(*BucketStore).LabelValues(0xc000336600, {0x25f3bd0, 0xc05d9ac4e0}, 0xc0a797bd40)
	/__w/mimir/mimir/pkg/storegateway/bucket.go:1288 +0xa3b fp=0xc0bbb9f320 sp=0xc0bbb9f168 pc=0x18e9e1b

...
```

#### Environment

- Mimir 2.5.0 from official image
- AWS EKS (Amazon Linux 2) on AMD (m5a and m6a nodes)
  - `Linux mimir-store-gateway-1 5.4.219-126.411.amzn2.x86_64 #1 SMP Wed Nov 2 17:44:17 UTC 2022 x86_64 Linux`
- 48 replicas w/ 4 CPU, 32gb RAM, 1000Gi gp2 EBS
- `blocks-storage.bucket-store.max-concurrent = 50`
- 60.8 million active series

**Comment by Packetslave** [comment] 2022-12-17 21:56
Oops, this may be a dup of #3522, but if so I can confirm it's still happening on 2.5.0

**Comment by pracucci** [comment] 2022-12-22 15:57
I also think it's a duplicate of https://github.com/grafana/mimir/issues/3522. Let's follow up there.

**Closed by pracucci** 2022-12-22 15:57 UTC
