### ISSUE TITLE
target_info metric

### ISSUE THREAD

**Issue by alexfalkowski** [grafana/mimir#7875] opened 2024-04-11 08:14 UTC
#### Describe the bug
Force pushing with otlpmetrichttp causes:

```
ts=2024-04-11T07:12:00.234987231Z caller=push.go:171 level=error user=anonymous msg="push error" err="failed pushing to ingester afalkowski: user=anonymous: the sample has been rejected because its timestamp is too old (err-mimir-sample-timestamp-too-old). The affected sample has timestamp 1970-01-01T00:00:00Z and is from series target_info{job=\"unknown_service:auth\", telemetry_sdk_language=\"go\", telemetry_sdk_name=\"opentelemetry\", telemetry_sdk_version=\"1.25.0\"}"
```

#### To Reproduce

Check out this comment https://github.com/open-telemetry/opentelemetry-go/issues/4133#issuecomment-2049086519

#### Expected behavior

This metric is only used by Prometheus. So it should not be used.

#### Environment

- Infrastructure: laptop
- Deployment tool: none

#### Additional Context

N/A

**Comment by aknuds1** [comment] 2024-04-11 09:33
> This metric is only used by Prometheus.

What do you mean by this? `target_info` is also relevant to users of Mimir.

**Comment by aknuds1** [comment] 2024-04-11 09:36
This is also looking like a dup of 7272 to me.

**Comment by alexfalkowski** [comment] 2024-04-11 09:39
> This is also looking like a dup of #7272 to me.

Thanks for the quick response. Yes I saw the issue and was not sure if they were related. Feel free to close if they are.

**Comment by aknuds1** [comment] 2024-04-11 09:41
To me it looks like the bug is that the `target_info` sample gets generated with an invalid timestamp (the Unix epoch).

**Comment by aknuds1** [comment] 2024-04-11 09:42
Closing as duplicate of #7272.

**Closed by aknuds1** 2024-04-11 09:42 UTC
Labels: question, area/opentelemetry
