### ISSUE TITLE
Mimirtool analyze listing used labels

### ISSUE THREAD

**Issue by whitepiratebaku** [grafana/mimir#4960] opened 2023-05-09 11:53 UTC
it is a feature request, currently mimirtool capable of analyzing used metrics based on dashboard/rules json/yaml files, it would be nice feature if it can extract used labels as well.

**Comment by bboreham** [comment] 2023-05-09 16:10
Closing as duplicate of #4959

**Closed by bboreham** 2023-05-09 16:10 UTC
Labels: duplicate
