### ISSUE TITLE
Buildinfo with prometheus prefix is only exposed by the queriers and query-frontends

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2678] opened 2022-08-09 12:01 UTC
The PR https://github.com/grafana/mimir/pull/1219 introduced three ednpoints similar to the buildinfo endpoint in prometheus.

* `/api/v1/status/buildinfo`
* `/prometheus/api/v1/status/buildinfo`
* `/alertmanager/api/v1/status/buildinfo`

The first is exposed on all mimir components ([code](https://github.com/grafana/mimir/blob/23afa077c31903a915da001692e276d59a43f7be/pkg/api/api.go#L226)). The second is only available on the querier and query-frontend APIs ([code](https://github.com/grafana/mimir/blob/23afa077c31903a915da001692e276d59a43f7be/pkg/api/api.go#L376)) The last one is only available on the alertmanager component ([code](https://github.com/grafana/mimir/blob/23afa077c31903a915da001692e276d59a43f7be/pkg/api/api.go#L201)).

The first and the last make sense. But I am not sure if the second endpoint prefixed with `/prometheus` shouldn't also be exposed on all components?

**Comment by pracucci** [comment] 2022-08-09 12:35
Currently the `/prometheus` prefix was intended to be used for Prometheus-compatibile API endpoints, which are only exposed by query-frontend, querier and ruler. That's the reason why it wasn't exposed on other services too.

**Comment by dimitarvdimitrov** [comment] 2022-08-09 12:43
This makes more sense. But the ruler doesn't expose the `/prometheus` endpoint. That looks like a bug

**Comment by pracucci** [comment] 2022-08-09 15:16
> This makes more sense. But the ruler doesn't expose the `/prometheus` endpoint. That looks like a bug

Agree. This should be fixed.

**Closed** 2022-08-16 09:34 UTC
Labels: question
