### ISSUE TITLE
Invalid query can result in 503 instead of 4xx

### ISSUE THREAD

**Issue by replay** [grafana/mimir#3523] opened 2022-11-24 17:49 UTC
#### Describe the bug
I have seen a user submit an invalid query which resulted in this error being returned from the query-frontend:

```
many-to-many matching not allowed: matching labels must be unique on one side
```

Then the query-frontend seems to cancel the request:

```
msg="error processing request" try=0 err="context canceled"
```

I believe that the canceled request then results in a `503` because the metric `cortex_request_duration_seconds_count` increases the counter with the label `status_code=503`

#### To Reproduce

Write a query resulting in the error `many-to-many matching not allowed: matching labels must be unique on one side` to reproduce

#### Expected behavior

An invalid query should result in `4xx` not `5xx`

#### Environment

Grafana Cloud

**Comment by francoposa** [comment] 2023-08-30 18:40
I have begun attempting to repro

Prometheus [`returnAPIError`](https://github.com/grafana/mimir/blob/c90ffeb4151a8c24088e2caeec5ad8f3eba98b89/vendor/github.com/prometheus/prometheus/web/api/v1/api.go#L620-L644)
will always report errors with this structure with `apiError.typ: errorExec`

Then in the same file, the [`respondError`](https://github.com/grafana/mimir/blob/c90ffeb4151a8c24088e2caeec5ad8f3eba98b89/vendor/github.com/prometheus/prometheus/web/api/v1/api.go#L1731-L1770) will transform all errors with `apiError.typ: errorExec` with an `code = http.StatusUnprocessableEntity`, which is 422.

This 422 code carries all the way up to the top of the querier's stack - next up is to see how it's handled in query-frontend.

I have not been able to repro getting anything other than a `400` from the frontend yet

**Comment by francoposa** [comment] 2023-08-30 21:09
query-frontend just forwards up the same code

**Comment by francoposa** [comment] 2023-08-30 21:37
I think what we have here is expected behavior, unless we can actually observe one of these queries cause a context canceled or 503 _on the same request_ that returns the `many-to-many matching not allowed` error.

Unlike other (maybe all other?) malformed-query-ish errors, this error actually has to execute the query before it knows that it `found duplicate series for the match group %s on the %s hand-side of the operation`.

So timeouts and context cancellations can occur in this query path, for the same bad query that can also return `many-to-many matching not allowed` - just not on the same request.
If the data is fetched without any sort of cancel or timeout, you get the 4xx error, if the data cannot be fetched or some other cancel or timeout occurs up the stack, you get the 5xx error.

If the query has to actually fetch data, that gives it a much higher possibility of experiencing a context cancellation for the request, vs. other kinds of malformed queries, which may be able to be validated before the query fetches any data.

Malformed queries that can be deemed malformed just by the parser, before any data is fetched, get an errorType `errorBadData`.
This error, returned with the message `many-to-many matching not allowed` has the errorType `errorExec` this is assigned down where the data fetch & query execution on the fetched data was attempted:

digging down into when prometheus engine actually uses `errorExec` in
https://github.com/grafana/mimir/blob/c90ffeb4151a8c24088e2caeec5ad8f3eba98b89/vendor/github.com/prometheus/prometheus/web/api/v1/api.go:
```go
	switch cause.(type) {
	case promql.ErrQueryCanceled:
		return &apiError{errorCanceled, err}
	case promql.ErrQueryTimeout:
		return &apiError{errorTimeout, err}
	case promql.ErrStorage:
		return &apiError{errorInternal, err}
	}

	if errors.Is(err, context.Canceled) {
		return &apiError{errorCanceled, err}
	}

	return &apiError{errorExec, err}
```

So getting an `errorExec` type essentially means "we got the data but could not correctly execute that query on the data".
Those other cases are where you would get a 500.

**Comment by francoposa** [comment] 2023-11-02 20:04
Essentially some bad queries have to fetch data before it's determined it's bad.
These queries can 4xx or 5xx.

It gives 4xx if it gets the data and then determines bad query for this data.

It gives 5xx if it fails to get the data due to context cancel/timeout/other internal error

**Comment by pracucci** [comment] 2023-11-16 11:10
> It gives 4xx if it gets the data and then determines bad query for this data.
> It gives 5xx if it fails to get the data due to context cancel/timeout/other internal error

Context cancellation shouldn't return a 5xx: if it does, then I think it's an issue. For the other cases, isn't expected that if a query times out we return 5xx?

**Comment by francoposa** [comment] 2024-01-25 19:15
you are right, it appears that the context canceled case `return &apiError{errorCanceled, err}` gets transformed into a 499. In the same file, we have
```golang
case errorCanceled:
	code = statusClientClosedConnection
```
and
```golang
// Non-standard status code (originally introduced by nginx) for the case when a client closes
	// the connection while the server is still processing the request.
	statusClientClosedConnection = 499
```

But yeah this appears to be expected behavior.

**Comment by francoposa** [comment] 2024-01-25 21:20
I am going to close this for the time being, as I do not believe there is any open question or investigation remaining.

In summary:
* series must be fetched in before the queriers can determine if a query will cause the error `many-to-many matching not allowed: matching labels must be unique on one side`
* failure to fetch the series due to some server-side issue such as a timeout will cause a 5xx.
  * new exception to this: upstream Prometheus changes now use 499 when the cause of failure is a context cancel - previously it was 503.
* successfully fetching the series, then applying the query and finding many-to-many matching will return the 422 as expected.

**Closed by francoposa** 2024-01-25 21:20 UTC
Labels: bug, component/query-frontend
