### ISSUE TITLE
Add support for S3-CMK (SSE-C)

### ISSUE THREAD

**Issue by udf2457** [grafana/mimir#7334] opened 2024-02-08 12:08 UTC
My understanding is that a present `mimir` only supports `SSE-S3` and `SSE-KMS` modes of encryption.

Please add support for `SSE-C` mode whereby the key can be provided by the caller (https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html).

This is important for two reasons:

1. sometimes regulatory or contractual reasons means that it is not possible to trust the cloud provider key management (or there are requirements for segregation of duties whereby the cloud provider cannot be both the data store and the key store)
2. there are implementations of S3 out there that only support `SSE-C` mode, for example Exosale Simple Object Storage: https://community.exoscale.com/documentation/storage/encryption/

**Comment by dimitarvdimitrov** [comment] 2024-02-08 16:18
is this a duplicate of https://github.com/grafana/mimir/issues/3381?

**Comment by andyasp** [comment] 2024-02-09 14:40
Closing as a duplicate https://github.com/grafana/mimir/issues/3381

**Closed by andyasp** 2024-02-09 14:40 UTC
